# Generated by Django 2.2.3 on 2019-08-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190807_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vgc',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
